Refactor patcher script for PnZH image handling

diff --git a/patcher b/patcher
--- a/patcher
+++ b/patcher
@@ -1,19 +1,19 @@
 #!/bin/bash
 #####=============== SMALLRAT TOOLBOX ===============#####
 function message() {
-   case $1 in
-   "error") echo "${bold}${red}[patcher.sh](error) => {$2}${normal}";;
-   "warning") echo "${bold}${yellow}[patcher.sh](warning) => {$2}${normal}";;
-   "success") echo "${bold}${green}[patcher.sh](success) -> [$2]${normal}";;
-   "info") echo "[patcher.sh](info) -> [$2]";;
-   *) return 1;;
-   esac
+   case $1 in
+   "error") echo "${bold}${red}[patcher.sh](error) => {$2}${normal}";;
+   "warning") echo "${bold}${yellow}[patcher.sh](warning) => {$2}${normal}";;
+   "success") echo "${bold}${green}[patcher.sh](success) -> [$2]${normal}";;
+   "info") echo "[patcher.sh](info) -> [$2]";;
+   *) return 1;;
+   esac
 }
 function existance() {
-   if [ -e $1 ];
-   then found=true && eval $2
-   else found=false && eval $3
-   fi
+   if [ -e $1 ];
+   then found=true && eval $2
+   else found=false && eval $3
+   fi
 }
 csd=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
 normal=$(tput sgr0)
@@ -30,17 +30,20 @@ pass=":"
 #####================================================#####
 
 # unzip or rename if necessary
-existance $csd/recovery.img.lz4 $pass $pass
+# Now checking for PnZH.img.lz4 or PnZH.img
+existance $csd/PnZH.img.lz4 $pass $pass
 if [ $found == true ]; then
-   message info "found lz4-zipped image! unzipping..." &&
-   lz4 -B6 --content-size -f $csd/recovery.img.lz4 && mv ./recovery.img ./raw.img &&
-   message success "unzipped to raw.img!"
-else existance $csd/recovery.img $pass $pass
-   if [ $found == true ]; then
-      mv $csd/recovery.img $csd/raw.img &&
-      message success "found unzipped image!"
-      else message error "no image to patch found. please place recovery.img.lz4 or recovery.img in folder" && exit
-   fi
+   message info "found lz4-zipped image! unzipping..." &&
+   # Renaming the lz4 file and unzipping it
+   lz4 -B6 --content-size -f $csd/PnZH.img.lz4 && mv ./PnZH.img ./raw.img &&
+   message success "unzipped to raw.img!"
+else existance $csd/PnZH.img $pass $pass
+   if [ $found == true ]; then
+      # Renaming the unzipped file to raw.img for processing
+      mv $csd/PnZH.img $csd/raw.img &&
+      message success "found unzipped image!"
+      else message error "no image to patch found. please place PnZH.img.lz4 or PnZH.img in folder" && exit
+   fi
 fi
 
 # edit raw image
@@ -100,28 +103,32 @@ message success "successfully finished patch to fragmented image!"
 
 # reassemble fragmented image
 message warning "attempting to defragment image! if your image is corrupted, this may not end well..."
-$csd/magiskboot repack $csd/header.img $csd/output.img
-existance $csd/output.img "message success 'assembled output.img!' && cd $csd" "message error 'failed to assemble image!' && exit 1"
+# Renaming output.img to PnZH_patched.img
+$csd/magiskboot repack $csd/header.img $csd/PnZH_patched.img
+existance $csd/PnZH_patched.img "message success 'assembled PnZH_patched.img!' && cd $csd" "message error 'failed to assemble image!' && exit 1"
 
 # sign patched image with keyfile
 message info "extracting public key to phh.pub.bin..."
 python3 $csd/avbtool extract_public_key --key $csd/keys/phh.pem --output $csd/keys/phh.pub.bin &&
 message info "signing patched image with key..."
-python3 $csd/avbtool add_hash_footer --image $csd/output.img --partition_name recovery --partition_size $(wc -c $csd/raw.img | cut -f 1 -d ' ') --key $csd/keys/phh.pem --algorithm SHA256_RSA4096 &&
+# Signing the new patched image name
+python3 $csd/avbtool add_hash_footer --image $csd/PnZH_patched.img --partition_name recovery --partition_size $(wc -c $csd/raw.img | cut -f 1 -d ' ') --key $csd/keys/phh.pem --algorithm SHA256_RSA4096 &&
 message success "signed image successfully!"
 
 # package image for use in odin
 message info "packaging image for odin..."
-tar -cvf $csd/output.tar $csd/output.img &&
+# Packaging the new patched image name
+tar -cvf $csd/PnZH_patched.tar $csd/PnZH_patched.img &&
 # hold off on this; what does it even do?
 # md5sum -t $csd/output.tar >> $csd/output.tar &&
 # mv $csd/output.tar $csd/output.tar.md5 &&
-message success "successfully packaged output.img -> output.tar"
+message success "successfully packaged PnZH_patched.img -> PnZH_patched.tar"
 
 # dispose of any unnecessary files
 message warning "cleaning up the directory..."
 sudo rm -rf $csd/fragments &&
 sudo rm -rf $csd/header.img &&
-mv $csd/raw.img $csd/recovery.img &&
+# Moving raw.img back to the original PnZH.img name
+mv $csd/raw.img $csd/PnZH.img &&
 sudo rm -rf $csd/keys/phh.pem &&
 message success "enjoy! hope what you're trying to do works."
