Update patcher script for PnZH image handling

diff --git a/patcher-minimal b/patcher-minimal
--- a/patcher-minimal
+++ b/patcher-minimal
@@ -1,25 +1,25 @@
 #!/bin/bash
 #####=============== SMALLRAT TOOLBOX ===============#####
 function existance() {
-   if [ -e $1 ];
-   then found=true && eval $2
-   else found=false && eval $3
-   fi
+   if [ -e $1 ];
+   then found=true && eval $2
+   else found=false && eval $3
+   fi
 }
 csd=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
 pass=":"
 #####================================================#####
 
 # exit or rename if necessary
-existance $csd/recovery.img.lz4 $pass $pass
+existance $csd/PnZH.img.lz4 $pass $pass
 if [ $found == true ]; then
-   echo "found lz4-zipped image! please unzip it yourself, and re-run this script! " && exit
-else existance $csd/recovery.img $pass $pass
-   if [ $found == true ]; then
-      mv $csd/recovery.img $csd/raw.img &&
-      echo "found unzipped image!"
-      else echo "no image to patch found. please place recovery.img in folder!" && exit 1
-   fi
+   echo "found lz4-zipped image! please unzip it yourself, and re-run this script! " && exit
+else existance $csd/PnZH.img $pass $pass
+   if [ $found == true ]; then
+      mv $csd/PnZH.img $csd/raw.img &&
+      echo "found unzipped image!"
+      else echo "no image to patch found. please place PnZH.img in folder!" && exit 1
+   fi
 fi
 
 # edit raw image
@@ -84,22 +84,22 @@ echo "successfully finished patch to fragmented image!"
 # reassemble fragmented image
 mkdir $csd/output
 echo "attempting to defragment image! if your image is corrupted, this may not end well..."
-$csd/magiskboot repack $csd/header.img $csd/output/output.img
-existance $csd/output/output.img "echo assembled output.img! && cd $csd" "echo output.img not found, exiting && exit 1"
+$csd/magiskboot repack $csd/header.img $csd/output/PnZH_patched.img
+existance $csd/output/PnZH_patched.img "echo assembled PnZH_patched.img! && cd $csd" "echo output.img not found, exiting && exit 1"
 
 # sign patched image with keyfile
 echo "extracting public key to phh.pub.bin..."
 python3 $csd/avbtool extract_public_key --key $csd/keys/phh.pem --output $csd/keys/phh.pub.bin &&
 echo "signing patched image with key..."
-python3 $csd/avbtool add_hash_footer --image $csd/output/output.img --partition_name recovery --partition_size $(wc -c $csd/raw.img | cut -f 1 -d ' ') --key $csd/keys/phh.pem --algorithm SHA256_RSA4096
+python3 $csd/avbtool add_hash_footer --image $csd/output/PnZH_patched.img --partition_name recovery --partition_size $(wc -c $csd/raw.img | cut -f 1 -d ' ') --key $csd/keys/phh.pem --algorithm SHA256_RSA4096
 echo "signed image successfully!"
 
 # package image for use in odin
 echo "packaging image for odin..."
-tar -cvf $csd/output/output.tar $csd/output/output.img &&
-md5sum -t $csd/output/output.tar >> $csd/output/output.tar &&
-mv $csd/output/output.tar $csd/output/output.tar.md5 &&
-echo "successfully packaged output.img -> output.tar.md5"
+tar -cvf $csd/output/PnZH_patched.tar $csd/output/PnZH_patched.img &&
+md5sum -t $csd/output/PnZH_patched.tar >> $csd/output/PnZH_patched.tar &&
+mv $csd/output/PnZH_patched.tar $csd/output/PnZH_patched.tar.md5 &&
+echo "successfully packaged PnZH_patched.img -> PnZH_patched.tar.md5"
 
 # hehe
 echo "enjoy! hope what you're trying to do works."
